aca_shop_homepage:
    path:     /hello/{name}/{age}
    defaults: { _controller: AcaShopBundle:Default:index }

aca_login_route:
    #this represents the URL
    path: /login_form
    #this represents the BundleFolder:ControllerName("Controller" is assumed):FunctionName("Action" is assumed)
    defaults: {_controller: AcaShopBundle:Default:loginForm }

aca_process_login_route:
    #this represents the URL
    path: /process_login
    #this represents the BundleFolder:ControllerName("Controller" is assumed):FunctionName("Action" is assumed)
    defaults: {_controller: AcaShopBundle:Default:processLogin }